<?php require('header.php'); 
echo "    <div>\n"; 
echo "        <ul class=\"breadcrumb\">\n"; 
echo "            <li>\n"; 
echo "                <a href=\"teacherpanel.php\">Home</a>\n"; 
echo "            </li>\n"; 
echo "            <li>\n"; 
echo "                <a href=\"search.php\">Student Search</a>\n"; 
echo "            </li>\n";
echo "\n"; 
echo "			&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\n"; 
echo "			&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\n"; 
echo "			&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;\n"; 
echo "				<a href=\"#\" onclick=\"history.go(-1)\" >Back</a>\n";
echo "        </ul>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <div class=\"row\">\n"; 
echo "    <div class=\"box col-md-12\">\n"; 
echo "    <div class=\"box-inner\">\n"; 
echo "    <div class=\"box-header well\" data-original-title=\"\">\n"; 
echo "        <h2><i class=\"glyphicon glyphicon-user\"></i>Details:Search</h2>\n"; 
echo "\n"; 
echo "        <div class=\"box-icon\">\n"; 
echo "            \n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <div class=\"box-content\">\n"; 
echo "    <table class=\"table table-bordered bootstrap-datatable responsive\">\n"; 
echo "        <form method=\"post\" action=\"viewDetails.php\">\n"; 
echo "            <tr>\n"; 
echo "                <td>Reg ID:</td>\n"; 
echo "                <td><input type=\"text\" name=\"regid\" /></td>\n"; 
echo "            </tr>\n"; 
echo "			<tr>\n"; 
echo "                <td>Name:</td>\n"; 
echo "                <td><input type=\"text\" name=\"fname\" /></td>\n"; 
echo "            </tr>\n"; 
echo "            \n"; 
echo "            <tr>\n"; 
echo "                <td>Sem:</td>\n"; 
echo "                <td><select type=\"text\" class=\"form-control\" placeholder=\"Sem\" name=\"Sem\" id=\"Sem\" value=\"\">\n"; 
echo "															<option value=\"\">Select Sem</option>\n"; 
echo "															<option value=\"1\">1</option>\n"; 
echo "															<option value=\"2\">2</option>\n"; 
echo "															<option value=\"3\">3</option>\n"; 
echo "															<option value=\"4\">4</option>\n"; 
echo "															<option value=\"5\">5</option>\n"; 
echo "															<option value=\"6\">6</option>\n"; 
echo "															<option value=\"7\">7</option>	\n"; 
echo "															<option value=\"8\">8</option>															\n"; 
echo "														</select></td>\n"; 
echo "            </tr>\n"; 
echo "            <tr>\n"; 
echo "                <td>Dept:</td>\n";
echo "\n"; 
echo "                <td><select type=\"text\" class=\"form-control\" name=\"Dept\" id=\"Dept\" value=\"\" required=\"\">\n";	
echo"                                               <option value=\"{$user_dept}\">{$user_dept}</option>\n";
echo "																</select></td>\n"; 
echo "            </tr>\n"; 
echo "            <tr>\n"; 
echo "                <td>Eligibility:</td>\n"; 
echo "                <td><select type=\"text\" class=\"form-control\" placeholder=\"Eligibility\" name=\"Eligibility\" id=\"Eligibility\" value=\"\">\n"; 
echo "															<option value=\"\">Eligibility</option>\n"; 
echo "															<option value=\"PASS\">PASS</option>\n"; 
echo "															<option value=\"FAIL\">FAIL</option>															\n"; 
echo "														</select></td>\n"; 
echo "            </tr>\n"; 
echo "            <tr>\n"; 
echo "                <td>&nbsp;</td>\n"; 
echo "                <td><input type=\"submit\" name=\"submit\" value=\"Search\" /></td>\n"; 
echo "            </tr>\n"; 
echo "        </form>\n"; 
echo "    </table>\n"; 
echo "    </div>\n"; 
echo "    </div>\n"; 
echo "    </div>\n"; 
echo "    <!--/span-->\n"; 
echo "\n"; 
echo "    </div><!--/row-->\n"; 
echo "\n"; 
 require('footer.php');
 ?>